name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '6 22 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Fetch latest data
      id: fetch
      run: |-
        bundle exec ruby scrape.rb >> $GITHUB_OUTPUT
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Store ranking updated. ${{ steps.fetch.outputs.ios_diff }}" || exit 0
        git push
